# MongoDB Configuration
spring.data.mongodb.uri=mongodb://tripplan1:123456@localhost:27017/tripplan?authSource=admin&readPreference=primary&appname=MongoDB%20Compass&directConnection=true&ssl=false

# Security Configuration
spring.security.user.name=sa
spring.security.user.password=sa123

# Server Configuration
server.port=8081


# Frontend Configuration
spring.web.resources.static-locations=classpath:/static/

# Enable Spring Security debug logging
logging.level.org.springframework.security=DEBUG
